/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as ProRevenusRouteImport } from './routes/pro.revenus'
import { Route as ProPrestationsRouteImport } from './routes/pro.prestations'
import { Route as ProParametresRouteImport } from './routes/pro.parametres'
import { Route as ProMessagesRouteImport } from './routes/pro.messages'
import { Route as ProDemandesRouteImport } from './routes/pro.demandes'
import { Route as ProClientsRouteImport } from './routes/pro.clients'
import { Route as ProAgendaRouteImport } from './routes/pro.agenda'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRevenusRoute = ProRevenusRouteImport.update({
  id: '/pro/revenus',
  path: '/pro/revenus',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPrestationsRoute = ProPrestationsRouteImport.update({
  id: '/pro/prestations',
  path: '/pro/prestations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProParametresRoute = ProParametresRouteImport.update({
  id: '/pro/parametres',
  path: '/pro/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProMessagesRoute = ProMessagesRouteImport.update({
  id: '/pro/messages',
  path: '/pro/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDemandesRoute = ProDemandesRouteImport.update({
  id: '/pro/demandes',
  path: '/pro/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProClientsRoute = ProClientsRouteImport.update({
  id: '/pro/clients',
  path: '/pro/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ProAgendaRoute = ProAgendaRouteImport.update({
  id: '/pro/agenda',
  path: '/pro/agenda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/calendrier': typeof CalendrierRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/demandes': typeof ProDemandesRoute
  '/pro/messages': typeof ProMessagesRoute
  '/pro/parametres': typeof ProParametresRoute
  '/pro/prestations': typeof ProPrestationsRoute
  '/pro/revenus': typeof ProRevenusRoute
  '/pro/': typeof ProIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/calendrier': typeof CalendrierRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/demandes': typeof ProDemandesRoute
  '/pro/messages': typeof ProMessagesRoute
  '/pro/parametres': typeof ProParametresRoute
  '/pro/prestations': typeof ProPrestationsRoute
  '/pro/revenus': typeof ProRevenusRoute
  '/pro': typeof ProIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/calendrier': typeof CalendrierRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/demandes': typeof ProDemandesRoute
  '/pro/messages': typeof ProMessagesRoute
  '/pro/parametres': typeof ProParametresRoute
  '/pro/prestations': typeof ProPrestationsRoute
  '/pro/revenus': typeof ProRevenusRoute
  '/pro/': typeof ProIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/auth'
    | '/avis'
    | '/calendrier'
    | '/favoris'
    | '/messages'
    | '/paiements'
    | '/parametres'
    | '/reservations'
    | '/reset-password'
    | '/pro/agenda'
    | '/pro/clients'
    | '/pro/demandes'
    | '/pro/messages'
    | '/pro/parametres'
    | '/pro/prestations'
    | '/pro/revenus'
    | '/pro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/auth'
    | '/avis'
    | '/calendrier'
    | '/favoris'
    | '/messages'
    | '/paiements'
    | '/parametres'
    | '/reservations'
    | '/reset-password'
    | '/pro/agenda'
    | '/pro/clients'
    | '/pro/demandes'
    | '/pro/messages'
    | '/pro/parametres'
    | '/pro/prestations'
    | '/pro/revenus'
    | '/pro'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/auth'
    | '/avis'
    | '/calendrier'
    | '/favoris'
    | '/messages'
    | '/paiements'
    | '/parametres'
    | '/reservations'
    | '/reset-password'
    | '/pro/agenda'
    | '/pro/clients'
    | '/pro/demandes'
    | '/pro/messages'
    | '/pro/parametres'
    | '/pro/prestations'
    | '/pro/revenus'
    | '/pro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  AuthRoute: typeof AuthRoute
  AvisRoute: typeof AvisRoute
  CalendrierRoute: typeof CalendrierRoute
  FavorisRoute: typeof FavorisRoute
  MessagesRoute: typeof MessagesRoute
  PaiementsRoute: typeof PaiementsRoute
  ParametresRoute: typeof ParametresRoute
  ReservationsRoute: typeof ReservationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProAgendaRoute: typeof ProAgendaRoute
  ProClientsRoute: typeof ProClientsRoute
  ProDemandesRoute: typeof ProDemandesRoute
  ProMessagesRoute: typeof ProMessagesRoute
  ProParametresRoute: typeof ProParametresRoute
  ProPrestationsRoute: typeof ProPrestationsRoute
  ProRevenusRoute: typeof ProRevenusRoute
  ProIndexRoute: typeof ProIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/revenus': {
      id: '/pro/revenus'
      path: '/pro/revenus'
      fullPath: '/pro/revenus'
      preLoaderRoute: typeof ProRevenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/prestations': {
      id: '/pro/prestations'
      path: '/pro/prestations'
      fullPath: '/pro/prestations'
      preLoaderRoute: typeof ProPrestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/parametres': {
      id: '/pro/parametres'
      path: '/pro/parametres'
      fullPath: '/pro/parametres'
      preLoaderRoute: typeof ProParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/messages': {
      id: '/pro/messages'
      path: '/pro/messages'
      fullPath: '/pro/messages'
      preLoaderRoute: typeof ProMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/demandes': {
      id: '/pro/demandes'
      path: '/pro/demandes'
      fullPath: '/pro/demandes'
      preLoaderRoute: typeof ProDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/clients': {
      id: '/pro/clients'
      path: '/pro/clients'
      fullPath: '/pro/clients'
      preLoaderRoute: typeof ProClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/agenda': {
      id: '/pro/agenda'
      path: '/pro/agenda'
      fullPath: '/pro/agenda'
      preLoaderRoute: typeof ProAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  AuthRoute: AuthRoute,
  AvisRoute: AvisRoute,
  CalendrierRoute: CalendrierRoute,
  FavorisRoute: FavorisRoute,
  MessagesRoute: MessagesRoute,
  PaiementsRoute: PaiementsRoute,
  ParametresRoute: ParametresRoute,
  ReservationsRoute: ReservationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProAgendaRoute: ProAgendaRoute,
  ProClientsRoute: ProClientsRoute,
  ProDemandesRoute: ProDemandesRoute,
  ProMessagesRoute: ProMessagesRoute,
  ProParametresRoute: ProParametresRoute,
  ProPrestationsRoute: ProPrestationsRoute,
  ProRevenusRoute: ProRevenusRoute,
  ProIndexRoute: ProIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
