/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ProRouteImport } from './routes/pro'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProRevenusRouteImport } from './routes/pro.revenus'
import { Route as ProPrestationsRouteImport } from './routes/pro.prestations'
import { Route as ProDemandesRouteImport } from './routes/pro.demandes'
import { Route as ProClientsRouteImport } from './routes/pro.clients'
import { Route as ProAgendaRouteImport } from './routes/pro.agenda'

const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRevenusRoute = ProRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => ProRoute,
} as any)
const ProPrestationsRoute = ProPrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => ProRoute,
} as any)
const ProDemandesRoute = ProDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => ProRoute,
} as any)
const ProClientsRoute = ProClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ProRoute,
} as any)
const ProAgendaRoute = ProAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/avis': typeof AvisRoute
  '/calendrier': typeof CalendrierRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pro': typeof ProRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/demandes': typeof ProDemandesRoute
  '/pro/prestations': typeof ProPrestationsRoute
  '/pro/revenus': typeof ProRevenusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/avis': typeof AvisRoute
  '/calendrier': typeof CalendrierRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pro': typeof ProRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/demandes': typeof ProDemandesRoute
  '/pro/prestations': typeof ProPrestationsRoute
  '/pro/revenus': typeof ProRevenusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/avis': typeof AvisRoute
  '/calendrier': typeof CalendrierRoute
  '/favoris': typeof FavorisRoute
  '/messages': typeof MessagesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pro': typeof ProRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/pro/agenda': typeof ProAgendaRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/demandes': typeof ProDemandesRoute
  '/pro/prestations': typeof ProPrestationsRoute
  '/pro/revenus': typeof ProRevenusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/avis'
    | '/calendrier'
    | '/favoris'
    | '/messages'
    | '/paiements'
    | '/parametres'
    | '/pro'
    | '/reservations'
    | '/pro/agenda'
    | '/pro/clients'
    | '/pro/demandes'
    | '/pro/prestations'
    | '/pro/revenus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/avis'
    | '/calendrier'
    | '/favoris'
    | '/messages'
    | '/paiements'
    | '/parametres'
    | '/pro'
    | '/reservations'
    | '/pro/agenda'
    | '/pro/clients'
    | '/pro/demandes'
    | '/pro/prestations'
    | '/pro/revenus'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/avis'
    | '/calendrier'
    | '/favoris'
    | '/messages'
    | '/paiements'
    | '/parametres'
    | '/pro'
    | '/reservations'
    | '/pro/agenda'
    | '/pro/clients'
    | '/pro/demandes'
    | '/pro/prestations'
    | '/pro/revenus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  AvisRoute: typeof AvisRoute
  CalendrierRoute: typeof CalendrierRoute
  FavorisRoute: typeof FavorisRoute
  MessagesRoute: typeof MessagesRoute
  PaiementsRoute: typeof PaiementsRoute
  ParametresRoute: typeof ParametresRoute
  ProRoute: typeof ProRouteWithChildren
  ReservationsRoute: typeof ReservationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/revenus': {
      id: '/pro/revenus'
      path: '/revenus'
      fullPath: '/pro/revenus'
      preLoaderRoute: typeof ProRevenusRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/prestations': {
      id: '/pro/prestations'
      path: '/prestations'
      fullPath: '/pro/prestations'
      preLoaderRoute: typeof ProPrestationsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/demandes': {
      id: '/pro/demandes'
      path: '/demandes'
      fullPath: '/pro/demandes'
      preLoaderRoute: typeof ProDemandesRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/clients': {
      id: '/pro/clients'
      path: '/clients'
      fullPath: '/pro/clients'
      preLoaderRoute: typeof ProClientsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/agenda': {
      id: '/pro/agenda'
      path: '/agenda'
      fullPath: '/pro/agenda'
      preLoaderRoute: typeof ProAgendaRouteImport
      parentRoute: typeof ProRoute
    }
  }
}

interface ProRouteChildren {
  ProAgendaRoute: typeof ProAgendaRoute
  ProClientsRoute: typeof ProClientsRoute
  ProDemandesRoute: typeof ProDemandesRoute
  ProPrestationsRoute: typeof ProPrestationsRoute
  ProRevenusRoute: typeof ProRevenusRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProAgendaRoute: ProAgendaRoute,
  ProClientsRoute: ProClientsRoute,
  ProDemandesRoute: ProDemandesRoute,
  ProPrestationsRoute: ProPrestationsRoute,
  ProRevenusRoute: ProRevenusRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  AvisRoute: AvisRoute,
  CalendrierRoute: CalendrierRoute,
  FavorisRoute: FavorisRoute,
  MessagesRoute: MessagesRoute,
  PaiementsRoute: PaiementsRoute,
  ParametresRoute: ParametresRoute,
  ProRoute: ProRouteWithChildren,
  ReservationsRoute: ReservationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
