// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const serverEnv = typeof process !== 'undefined' ? process.env : {};
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || serverEnv.SUPABASE_URL;
const supabasePublishableKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  serverEnv.SUPABASE_ANON_KEY ||
  serverEnv.SUPABASE_PUBLISHABLE_KEY;

/**
 * False when the Lovable/Vercel preview has lost its injected Supabase variables.
 * The public mock experience must remain renderable in that situation instead of
 * crashing the whole React tree.
 */
export const isSupabaseConfigured = Boolean(supabaseUrl && supabasePublishableKey);

function createSupabaseClient() {
  if (!isSupabaseConfigured) {
    console.warn(
      '[Supabase] Environment variables are missing. Booker is running in safe mock mode until Supabase is reconnected.',
    );
  }

  const resolvedUrl = supabaseUrl || 'https://placeholder.supabase.co';
  const resolvedKey = supabasePublishableKey || 'placeholder-anon-key';

  return createClient<Database>(resolvedUrl, resolvedKey, {
    global: {
      fetch: createSupabaseFetch(resolvedKey),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: isSupabaseConfigured,
      autoRefreshToken: isSupabaseConfigured,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
